version: "3.7"

name: newoola

services:

  places_service:
    build: ./services/content
    container_name: "content_service"
    volumes:
      - ./services/content/src:/code/src
    ports:
      - 8001:8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - content_db

  content_db:
    image: mongo:8.0.1
    container_name: "content_db"
    ports:
      - '27017:27017'
    volumes:
      - mongodb_newoola_content_data:/data/db
    environment:
      - "MONGO_INITDB_DATABASE=newoola_content"
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=password"

  # fetcher_service:
  #   build: ./services/fetcher
  #   container_name: "fetcher_service"
  #   command: celery -A src.main worker --loglevel=info
  #   volumes:
  #     - ./services/fetcher/src:/code/src
  #   # ports:
  #   #   - 8001:8000
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   depends_on:
  #     - redis

  redis:
    image: redis:6.0-alpine
    container_name: "redis"
    ports:
      - "6379:6379"

  celery_worker:
    build: ./services/fetcher
    container_name: "celery_worker"
    command: celery -A src.celery worker --concurrency=4 --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build: ./services/fetcher
    container_name: "celery_beat"
    command: celery -A src.celery beat --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  flower:
    image: mher/flower
    container_name: "flower"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  mongodb_newoola_content_data:
