FROM python:3.11-alpine

# ENV PYTHONUNBUFFERED=1

# # Create the log file to be able to run tail
# RUN mkdir /var/log/termite
# RUN touch /var/log/termite/cron.log

# # Installing cron
# RUN apt-get -y update && apt-get -y upgrade
# RUN apt-get install -y cron htop

# # Install monitoring dependency
# RUN apt-get update && \
#     apt-get install -y unzip jq htop stress bc wget vim nano && \
#     wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" && \
#     unzip awscliv2.zip && \
#     ./aws/install && \
#     rm awscliv2.zip


# # Add crontab file in the cron directory
# COPY /config/cron/crontab /etc/cron.d/termite

# # Give execution rights on the cron job
# RUN chmod 0644 /etc/cron.d/termite

# # Apply cron job
# RUN crontab /etc/cron.d/termite

WORKDIR /code

# Install the package dependencies in the requirements file.
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt

COPY . /code/

# Run the command on container startup
CMD echo "Starting FETCHER..."; \
    python3 ./src/main.py -j cache -i 0;
# sleep 60; \
# printenv > .env; \
# echo "Filling cache.."; \
# python3 ./src/init.py -j cache -i 0; \
# nohup ./monitoring/HighUtilization.sh > ./logs/highutilization.log 2>&1 & \
# echo "Starting cron..."; \
# exec cron -f ;